### ISSUE TITLE
Can't compile with the commands provided in the readme

### ISSUE THREAD

**Issue by Frederik-Baetens** [level1wendell/memcpy_sse#1]
I tried to compile the code, with the following command, as provided in the readme:

`gcc -march=sse3 -O3 -m32 testmem_modified.c -o tm32`

but i get this error:

cc1: error: bad value (‘sse3’) for ‘-march=’ switch
cc1: note: valid arguments to ‘-march=’ switch are: i386 i486 i586 pentium lakemont pentium-mmx winchip-c6 winchip2 c3 samuel-2 c3-2 nehemiah c7 esther i686 pentiumpro pentium2 pentium3 pentium3m pentium-m pentium4 pentium4m prescott nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm geode k6 k6-2 k6-3 athlon athlon-tbird athlon-4 athlon-xp athlon-mp x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native

**Comment by DarrenRainey** [comment]
what version of gcc are you using and what cpu?

**Comment by DarrenRainey** [comment]
also sse3 is not a valid option you would need to  use one of the appropriate options for your system such as athlon64-sse3

**Comment by Frederik-Baetens** [comment]
Ah that wasn't clear to me from the readme, sorry.
